# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ccfn_tasks import download_smart_observations as download_smart_observations
from ccfn_tasks import download_smart_patrols as download_smart_patrols
from ccfn_tasks import draw_lcc_map as draw_lcc_map
from ccfn_tasks import draw_lcc_stat as draw_lcc_stat
from ccfn_tasks import draw_lcc_table as draw_lcc_table
from ccfn_tasks import draw_patrol_chart as draw_patrol_chart
from ccfn_tasks import draw_patrol_map as draw_patrol_map
from ccfn_tasks import draw_species_chart as draw_species_chart
from ccfn_tasks import draw_species_map as draw_species_map
from ccfn_tasks import estimate_conservancy_boundary as estimate_conservancy_boundary
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from esri_tasks import (
    get_esri_land_cover_change_events as get_esri_land_cover_change_events,
)
from wt_task import task

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            description="Download animal observation and patrol effort data from the CCFN SMART Connect server for the selected time range and visualise by conservancy and species. Land cover change detection uses the Esri 10m Annual LULC dataset via Microsoft Planetary Computer (no Google Earth Engine account required).",
            **(params_dict.get("workflow_details") or {}),
        )
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    observations = (
        task(download_smart_observations)
        .validate()
        .set_task_instance_id("observations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            connection="ccfn",
            time_range=time_range,
            **(params_dict.get("observations") or {}),
        )
        .call()
    )

    patrols = (
        task(download_smart_patrols)
        .validate()
        .set_task_instance_id("patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            connection="ccfn",
            time_range=time_range,
            min_patrol_km=5.0,
            **(params_dict.get("patrols") or {}),
        )
        .call()
    )

    conservancy_boundary = (
        task(estimate_conservancy_boundary)
        .validate()
        .set_task_instance_id("conservancy_boundary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=patrols,
            buffer_km=3.0,
            hull_percentile=95.0,
            **(params_dict.get("conservancy_boundary") or {}),
        )
        .call()
    )

    lcc_events = (
        task(get_esri_land_cover_change_events)
        .validate()
        .set_task_instance_id("lcc_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            roi=conservancy_boundary,
            time_range=time_range,
            change_from_classes="trees,flooded_vegetation,rangeland",
            change_to_classes="crops,built",
            min_area_ha=0.1,
            max_events=2000,
            resolution_deg=0.0001,
            **(params_dict.get("lcc_events") or {}),
        )
        .call()
    )

    lcc_map = (
        task(draw_lcc_map)
        .validate()
        .set_task_instance_id("lcc_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            lcc_events=lcc_events,
            boundary=conservancy_boundary,
            time_range=time_range,
            **(params_dict.get("lcc_map") or {}),
        )
        .call()
    )

    lcc_table = (
        task(draw_lcc_table)
        .validate()
        .set_task_instance_id("lcc_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            lcc_events=lcc_events,
            time_range=time_range,
            **(params_dict.get("lcc_table") or {}),
        )
        .call()
    )

    lcc_total_ha = (
        task(draw_lcc_stat)
        .validate()
        .set_task_instance_id("lcc_total_ha")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            lcc_events=lcc_events,
            time_range=time_range,
            **(params_dict.get("lcc_total_ha") or {}),
        )
        .call()
    )

    obs_map = (
        task(draw_species_map)
        .validate()
        .set_task_instance_id("obs_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=observations,
            boundary=conservancy_boundary,
            time_range=time_range,
            **(params_dict.get("obs_map") or {}),
        )
        .call()
    )

    obs_chart = (
        task(draw_species_chart)
        .validate()
        .set_task_instance_id("obs_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=observations,
            time_range=time_range,
            **(params_dict.get("obs_chart") or {}),
        )
        .call()
    )

    patrol_map = (
        task(draw_patrol_map)
        .validate()
        .set_task_instance_id("patrol_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=patrols,
            boundary=conservancy_boundary,
            time_range=time_range,
            **(params_dict.get("patrol_map") or {}),
        )
        .call()
    )

    patrol_chart = (
        task(draw_patrol_chart)
        .validate()
        .set_task_instance_id("patrol_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=patrols,
            time_range=time_range,
            **(params_dict.get("patrol_chart") or {}),
        )
        .call()
    )

    obs_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("obs_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=obs_map,
            **(params_dict.get("obs_map_html") or {}),
        )
        .call()
    )

    obs_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("obs_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=obs_chart,
            **(params_dict.get("obs_chart_html") or {}),
        )
        .call()
    )

    patrol_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=patrol_map,
            **(params_dict.get("patrol_map_html") or {}),
        )
        .call()
    )

    patrol_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("patrol_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=patrol_chart,
            **(params_dict.get("patrol_chart_html") or {}),
        )
        .call()
    )

    lcc_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("lcc_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=lcc_map,
            **(params_dict.get("lcc_map_html") or {}),
        )
        .call()
    )

    lcc_table_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("lcc_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=lcc_table,
            **(params_dict.get("lcc_table_html") or {}),
        )
        .call()
    )

    lcc_stat_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("lcc_stat_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=lcc_total_ha,
            **(params_dict.get("lcc_stat_html") or {}),
        )
        .call()
    )

    obs_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("obs_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Animal Observations Map",
            view=None,
            data=obs_map_html,
            **(params_dict.get("obs_map_widget") or {}),
        )
        .call()
    )

    obs_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("obs_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Animal Observations by Month",
            view=None,
            data=obs_chart_html,
            **(params_dict.get("obs_chart_widget") or {}),
        )
        .call()
    )

    patrol_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Effort Map",
            view=None,
            data=patrol_map_html,
            **(params_dict.get("patrol_map_widget") or {}),
        )
        .call()
    )

    patrol_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("patrol_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Patrol Effort by Month",
            view=None,
            data=patrol_chart_html,
            **(params_dict.get("patrol_chart_widget") or {}),
        )
        .call()
    )

    lcc_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("lcc_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Land Cover Change Map",
            view=None,
            data=lcc_map_html,
            **(params_dict.get("lcc_map_widget") or {}),
        )
        .call()
    )

    lcc_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("lcc_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Land Cover Change Events",
            view=None,
            data=lcc_table_html,
            **(params_dict.get("lcc_table_widget") or {}),
        )
        .call()
    )

    lcc_total_ha_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("lcc_total_ha_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Area Changed (ha)",
            view=None,
            data=lcc_stat_html,
            **(params_dict.get("lcc_total_ha_widget") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                obs_map_widget,
                obs_chart_widget,
                patrol_map_widget,
                patrol_chart_widget,
                lcc_map_widget,
                lcc_table_widget,
                lcc_total_ha_widget,
            ],
            groupers=[{"index_name": "All"}],
            time_range=time_range,
            **(params_dict.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
